export const SAMPLE_ACTION = 'SAMPLE_ACTION';

// go through reducer
export const ADD_TASK_FROM_SEARCH_TERM = 'ADD_TASK_FROM_SEARCH_TERM';
export const GET_CURRENT_TASK = 'GET_CURRENT_TASK';
export const ADD_A_PIECE_FOR_CURRENT_TASK = 'ADD_A_PIECE_FOR_CURRENT_TASK';
export const GET_CURRENT_TASK_OPTIONS = 'GET_CURRENT_TASK_OPTIONS';
export const GET_CURRENT_TASK_DIMENSIONS = 'GET_CURRENT_TASK_DIMENSIONS';
export const GET_CURRENT_TASK_OP_AND_DIMS = 'GET_CURRENT_TASK_OP_AND_DIMS';