/* SAMPLE ACTIONS */
export const SAMPLE_ACTION = 'SAMPLE_ACTION';
export const SAMPLE_ADD_TO_LIST = 'SAMPLE_ADD_TO_LIST';
export const SAMPLE_UPDATE_ELEMENT_IN_LIST = 'SAMPLE_UPDATE_ELEMENT_IN_LIST';

/* Plugin-level */
export const SWITCH_PLUGIN_WORKING_STATUS = 'SWITCH_PLUGIN_WORKING_STATUS';

/* Tasks */
export const ADD_TASK_FROM_SEARCH_TERM = 'ADD_TASK_FROM_SEARCH_TERM';
export const SWITCH_CURRENT_TASK = 'SWITCH_CURRENT_TASK';
export const DELETE_TASK_WITH_ID = 'DELETE_TASK_WITH_ID';
export const SWITCH_STAR_STATUS_OF_SELECTED_TASK = 'SWITCH_STAR_STATUS_OF_SELECTED_TASK';
export const SWITCH_STATUS_FOR_STAY_IN_THE_SAME_TASK = 'SWITCH_STATUS_FOR_STAY_IN_THE_SAME_TASK';
export const COMBINE_SOURCE_TASK_WITH_TARGET_TASK = 'COMBINE_SOURCE_TASK_WITH_TARGET_TASK';
// requests that don't go through firebase:
export const GET_CURRENT_TASK = 'GET_CURRENT_TASK';

/* Page visits count */
export const ADD_A_PAGE_TO_COUNT_LIST = 'ADD_A_PAGE_TO_COUNT_LIST';
export const DELETE_A_PAGE_FROM_COUNT_LIST = 'DELETE_A_PAGE_FROM_COUNT_LIST';

/* Options */
export const ADD_AN_OPTION_TO_CURRENT_TASK = 'ADD_AN_OPTION_TO_CURRENT_TASK';
export const DELETE_OPTION_WITH_ID = 'DELETE_OPTION_WITH_ID';

/* Pieces */
export const ADD_A_PIECE_TO_CURRENT_TASK = 'ADD_A_PIECE_TO_CURRENT_TASK';
export const DELETE_A_PIECE_WITH_ID = 'DELETE_A_PIECE_WITH_ID';
export const UPDATE_A_PIECE_WITH_ID = 'UPDATE_A_PIECE_WITH_ID';

/* Piece Group */
export const CREATE_A_PIECE_GROUP_WITH_TWO_PIECES = 'CREATE_A_PIECE_GROUP_WITH_TWO_PIECES';
export const CHANGE_NAME_OF_GROUP_WITH_ID = 'CHANGE_NAME_OF_GROUP_WITH_ID';
export const UPDATE_A_PIECE_GROUP_ATTITUDE_OPTION_PAIRS_WITH_ID = 'UPDATE_A_PIECE_GROUP_ATTITUDE_OPTION_PAIRS_WITH_ID';
export const ADD_A_PIECE_TO_A_GROUP = 'ADD_A_PIECE_TO_A_GROUP';
export const DETACH_A_PIECE_FROM_A_GROUP = 'DETACH_A_PIECE_FROM_A_GROUP';
export const DELETE_A_PIECE_GROUP = 'DELETE_A_PIECE_GROUP';

/* context menu */
export const ADD_OPTION_CONTEXT_MENU_CLICKED = 'ADD_OPTION_CONTEXT_MENU_CLICKED';
export const ADD_PIECE_CONTEXT_MENU_CLICKED = 'ADD_PIECE_CONTEXT_MENU_CLICKED';